name: t4h - CI
on: [pull_request]
env:
  # To force cache update
  CACHE_NUMBER: 0
jobs:
  tests:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Install Miniconda & Env
      #   uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     python-version: '3.11'
      #     activate-environment: t4h
      #     channel-priority: strict
      #     environment-file: environment.yml

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: t4h
          python-version: '3.11'
          use-mamba: true

      - name: Cache Conda env
        uses: actions/cache@v2
        with:
          path: ${{ env.CONDA }}/envs
          key:
            conda-${{ runner.os }}--${{ runner.arch }}--${{ hashFiles('environment.yml') }}-${{ env.CACHE_NUMBER }}
        id: cache

      - name: Update environment
        run:
          mamba env update -n t4h -f
          environment.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: PowerShell Core
        shell: pwsh
        run: |
          conda info
          conda list

      - name: Pytest & Coverage
        shell: powershell
        run: |
          C:\Miniconda\condabin\conda.bat activate t4h
          python -c "import sys; print(sys.version)"
          coverage run --source=./src -m pytest -v -s

      - name: Coverage Report Generation
        shell: powershell
        run: |
          C:\Miniconda\condabin\conda.bat activate t4h
          coverage xml

      - name: Lint black formatting
        shell: powershell
        run: black --check ./**/*.py
